-- MySQL Script generated by MySQL Workbench
-- jue 27 ene 2022 23:31:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joker_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joker_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joker_system` ;
USE `joker_system` ;

-- -----------------------------------------------------
-- Table `joker_system`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joker_system`.`ADMINISTRADOR` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `ci` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joker_system`.`PROFESOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joker_system`.`PROFESOR` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `ci` VARCHAR(15) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `ADMINISTRADOR_id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_profesor`, `ADMINISTRADOR_id_administrador`),
  INDEX `fk_PROFESOR_ADMINISTRADOR_idx` (`ADMINISTRADOR_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_ADMINISTRADOR`
    FOREIGN KEY (`ADMINISTRADOR_id_administrador`)
    REFERENCES `joker_system`.`ADMINISTRADOR` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joker_system`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joker_system`.`CURSO` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `video` BLOB NOT NULL,
  `descripcion` VARCHAR(65) NOT NULL,
  `PROFESOR_id_profesor` INT NOT NULL,
  `PROFESOR_ADMINISTRADOR_id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_curso`, `PROFESOR_id_profesor`, `PROFESOR_ADMINISTRADOR_id_administrador`),
  INDEX `fk_CURSO_PROFESOR1_idx` (`PROFESOR_id_profesor` ASC, `PROFESOR_ADMINISTRADOR_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_PROFESOR1`
    FOREIGN KEY (`PROFESOR_id_profesor` , `PROFESOR_ADMINISTRADOR_id_administrador`)
    REFERENCES `joker_system`.`PROFESOR` (`id_profesor` , `ADMINISTRADOR_id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
